### ISSUE TITLE
Problem in support for MOD04_3K

### ISSUE THREAD

**Issue by caijun** [dawhite/MCTK#10]
Hi dawhite,
Your MCTK is a useful tool for processing MODIS products. Thank you very much.
When I use MCTK to process MOD04_3K product under ENVI/IDL 4.5 on Windows 7, the interactive way  works properly; however, the programming way doesn't produce any outputs. The following is my script, which is customized based on the `Level 2 swath example` from the user's guide.

```
; Level 2 swath example
PRO TEST_BATCH_MODIS_CONVERSION_L2_SWATH
  COMPILE_OPT idl2

  modis_swath_file = 'C:\MCTK_Input\MOD04_3K.A2014335.0310.006.2015030045227.hdf'

  ; The specified output location MUST end in the appropriate path
  ; separator for your OS
  output_location = 'C:\MCTK_Output\'

  output_rootname = 'AOD'
  swath_name = 'mod04'

  sd_names = ['Optical_Depth_Land_And_Ocean', 'Aerosol_Type_Land']

  ; Output method schema is:
  ; 0 = Standard, 1 = Projected, 2 = Standard and Projected
  out_method = 1

  output_projection = ENVI_PROJ_CREATE(/geographic)

  ; Choosing nearest neighbor interpolation
  interpolation_method = 0

  ; do not put the bridge creation/destruction code inside a loop
  bridges = mctk_create_bridges()

  convert_modis_data, in_file=modis_swath_file, $
    out_path=output_location, out_root=output_rootname, $
    swt_name=swath_name,$
    sd_names=sd_names, $
    out_method=out_method, out_proj=output_projection, $
    interp_method=interpolation_method, /no_msg, $
    r_fid_array=r_fid_array, r_fname_array=r_fname_array, $
    bridges=bridges,msg=msg

  mctk_destroy_bridges, bridges
END
```

The same problem also occurs under ENVI/IDL 5.3. Moreover, under ENVI/IDL 5.3, the `Level 2 swath example` can't work and doesn't produce any outputs.

**Comment by dawhite** [comment]
I haven't built or tested against 5.3 yet and I am aware that there are some issues with MCTK and that version of ENVI.  My best guess about your script is that you are incorrectly specifying the input filepath and output directory.  Below is essentially your exact same script, but I substituted dialog_pickfile() calls for the inputs and outputs.  It runs as expected.  You can try printing those variables to see how they should be supplied programmatically.  I also added a line at the end the which prints out the msg variable if there is something in it.  That variable is there so you can catch issues like this.

;Level 2 swath example
pro test_batch_modis_conversion_l2_swath
  compile_opt idl2
  modis_swath_file = dialog_pickfile()
  if modis_swath_file eq '' then return
  ;The specified output location MUST end in the appropriate path
  ;separator for your OS
  output_location = dialog_pickfile(/directory)
  if output_location eq '' then return
  output_rootname = 'AOD'
  swath_name = 'mod04'
  sd_names = ['Optical_Depth_Land_And_Ocean', 'Aerosol_Type_Land']
  ;Output method schema is:
  ;0 = Standard, 1 = Projected, 2 = Standard and Projected
  out_method = 1
  output_projection = envi_proj_create(/geographic)
  ;Choosing nearest neighbor interpolation
  interpolation_method = 0
  ;do not put the bridge creation/destruction code inside a loop
  bridges = mctk_create_bridges()
  convert_modis_data, in_file=modis_swath_file, $
    out_path=output_location, out_root=output_rootname, $
    swt_name=swath_name, sd_names=sd_names, $
    out_method=out_method, out_proj=output_projection, $
    interp_method=interpolation_method, /no_msg, $
    r_fid_array=r_fid_array, r_fname_array=r_fname_array, $
    bridges=bridges, msg=msg
  mctk_destroy_bridges, bridges
  
  ;print any error messages
  if msg ne '' then print, msg
  
end

**Comment by caijun** [comment]
Thank you for your quick response. I just  carefully checked the inputs and outputs, and found I made two mistakes: the input hdf filename is not correct and the output location doesn't exist. Without substituting `dialog_pickfile()` calls for the inputs and outputs, the script also works well under both ENVI/IDL 5.3 on Windows 10 and ENVI/IDL 4.5 on Windows 7. I hope this testing information could be useful.

**Comment by dawhite** [comment]
That information is useful--thank you.  And I'm glad MCTK is working for you now.

**Comment by dawhite** [comment]
And be sure to grab the latest version (2.1.0), which I just released today.

**Comment by caijun** [comment]
Thanks for your notification. I have upgraded MCTK to version 2.1.0. I will report the testing information.

**Comment by onlyhesam** [comment]
I am very new to IDL programming. I have 15,000 MODIS HDF files and I want to know that is there any way to use MCTK plugin in IDL to convert all my HDF files automatically? As we know MCTK can only process one file at a time so if I want to use MCTK through its GUI in ENVI to convert this amount of HDF files, it will take a month to finish. Therefore I think there should be another way. 
I would appreciate you if you can help me.

**Comment by onlyhesam** [comment]
I have also run the MCTK in IDL 


;Level 2 swath example
pro test_batch_modis_conversion_l2_swath
  compile_opt idl2

  modis_swath_file = **'D:\THesis\MODIS\test\MOD04_L2.A2010001.0745.006.2015041174018.hdf'**

  ;The specified output location MUST end in the appropriate path
  ;separator for your OS
  output_location = **'D:\THesis\MODIS\output_2010\'**

  output_rootname = 'atm_profile'

  swath_name = 'mod04'

  sd_names = ['Optical_Depth_Land_And_Ocean']

  ;Output method schema is:
  ;0 = Standard, 1 = Projected, 2 = Standard and Projected
  out_method = 1

  output_projection = envi_proj_create(/geographic)

  ;Choosing nearest neighbor interpolation
  interpolation_method = 0

  ;do not put the bridge creation/destruction code inside a loop
  bridges = mctk_create_bridges()

  convert_modis_data, in_file=modis_swath_file, $
    out_path=output_location, out_root=output_rootname, $
    swt_name=swath_name, sd_names=sd_names, $
    out_method=out_method, out_proj=output_projection, $
    interp_method=interpolation_method, /no_msg, $
    r_fid_array=r_fid_array, r_fname_array=r_fname_array, $
    bridges=bridges, msg=msg

  mctk_destroy_bridges, bridges

end



but I received this error 

IDL> test_batch_modis_conversion_l2_swath
% Compiled module: TEST_BATCH_MODIS_CONVERSION_L2_SWATH.
% Attempt to call undefined function: 'ENVI_PROJ_CREATE'.
% Execution halted at: TEST_BATCH_MODIS_CONVERSION_L2_SWATH   21 D:\THesis\MODIS\test\test_batch_modis_conversion_l2_swath.pro
%                      $MAIN$          
IDL> 
Can you debug it please?

**Comment by caijun** [comment]
Before running your procedure, please type `envi` in IDL command line to load envi functions

```
IDL> envi
```

or you can call restore the base ENVI save files in your procedure by 

```
ENVI, /RESTORE_BASE_SAVE_FILES
ENVI_BATCH_INIT, /NO_STATUS_WINDOW

your code ...

ENVI_BATCH_EXIT
```
please read the documentation or refer to my code.

http://www.harrisgeospatial.com/docs/ENVI_Procedure.html

https://github.com/caijun/LCF/blob/master/detect_lc_from_mod35.pro

**Comment by onlyhesam** [comment]
Thank a lot. It solves my problem and the code has run perfectly. but there is another problem. how can I perform this code for a lot a HDF files simultaneously? for example, is it possible to add a "for loop" to this code?

**Comment by caijun** [comment]
Of course, you should learn how write for loop in IDL.
