### ISSUE TITLE
Unable to attach to supplied HDF file using grid approach

### ISSUE THREAD

**Issue by am2222** [dawhite/MCTK#12]
Hi,
I am using idl to loop for about 400 hdf files..But I faced this error using mckt,Can you please help me to find the rresion of this error?

Thank you
`<
 ;envi

 print,'Read hdf file';
 LIST=FINDFILE('D:\hdf\*.hdf');
 bridges = mctk_create_bridges()
 
  FOR f=0,(LIST.LENGTH-1) Do begin
    print,'read file '+ string(f) + ' of '+string(LIST.LENGTH)
    
  
 print,'read file '+ string(f) + ' of '+string(LIST.LENGTH)
 modis_swath_file =  LIST[f]
 ;The specified output location MUST end in the appropriate path
 ;separator for your OS
 output_location = 'D: \MCTK_Output\'
 output_rootname = 'level_2a'
 ;Output method schema is:
 ;0 = Standard, 1 = Projected, 2 = Standard and Projected
 out_method = 2
 output_projection = envi_proj_create(/geographic)
 ;Choosing linear interpolation
 interpolation_method = 1
 ;do not put the bridge creation/destruction code inside a loop
 sd_names = [ 'LST_Day_1km' , 'LST_Night_1km' ]
  convert_modis_data, in_file=modis_swath_file, $
    out_path=output_location, out_root=output_rootname, $
    sd_names=sd_names, $
    out_method=out_method,  $
    interp_method=interpolation_method,  $
    bridges=bridges, msg=msg
    ENDFOR
   mctk_destroy_bridges, bridges  
   
   print,msg
 end>`

**Comment by am2222** [comment]
sorry I forgot to say that I am working with MOD11A2 product

**Comment by dawhite** [comment]
I'm not seeing an error message in what you posted.  You are using the MSG keyword and printing it, which is good, but that should really be done inside the loop so you can get a status update after every conversion.  Is it printing anything now?  At first glance, I see a lot of beginner IDL programming mistakes in your code, like using the same output rootname for every file.  Be sure to test your code without a loop first, then generalize.  If you are just starting out, I recommend contacting Exelis/Harris technical support.  They can provide some general guidance on how to properly construct the loop.

**Comment by dawhite** [comment]
Oh, I see, the error is in the name of the issue you submitted. Sorry about that. In addition to many beginner programming errors, it looks like you left out the GD_NAME keyword.  See page 19 of the user guide.  For MOD11A2, the grid name is 'MODIS_Grid_8Day_1km_LST'.

**Comment by am2222** [comment]
Dear dawhite,
Thank you for your help,I checked and the previous error disapeard,But now a new error apeard.
WIDGET_BASE: Invalid widget identifier: 19.

It could you please guide me with it?
this is code that I use to convert one file

 bridges = mctk_create_bridges()
 

 ;   print,'read file '+ string(f) + ' of '+string(LIST.LENGTH)

 modis_swath_file = 'D:\\hdf\\MOD11A2.A2008121.h22v05.006.2015349103528.hdf'
 ;The specified output location MUST end in the appropriate path
 ;separator for your OS
 output_location = 'D:\MCTK_Output\'
 output_rootname = 'level_2a'
 ;Output method schema is:
 ;0 = Standard, 1 = Projected, 2 = Standard and Projected
 out_method = 2
 ;output_projection = envi_proj_create(/geographic)
 ;Choosing linear interpolation
 interpolation_method = 1
 ;do not put the bridge creation/destruction code inside a loop
 sd_names = [ 'LST_Day_1km' , 'LST_Night_1km' ]
  grid_name = 'MODIS_Grid_8Day_1km_LST'
  convert_modis_data, in_file=modis_swath_file, $
    gd_name=grid_name, sd_names=sd_names,out_path=output_location, out_root=output_rootname, /no_msg, $
    ;sd_names=sd_names, $
    out_method=out_method,  $
    bridges=bridges, msg=msg
mctk_destroy_bridges, bridges  

thank you so much

**Comment by dawhite** [comment]
That is a more general ENVI/IDL error, but it pointed me to an underlying issue with MCTK. You attempted to do something I hadn't anticipated, which was converting a GRID file using modified SWATH sample code.  The example you want to follow is on page 19 of the user guide. With that said, I want to fix the issue in case anyone tries this again, so I will do that and then post a new release.  I will also post some new sample code you can follow.  It might be a few days.

**Comment by am2222** [comment]
Thank you for your answer,I faces sth strange. I could convert mod11 using mckt extention before.But now I could not do it even using UI,I think sth is wrong with SWATH code as you said.

So I wait for new version and the error will be fixed?Sorry I dont have any idea how to use idl.I have worked with C# and java.I would like to help with this project,anyway thank you so much for your time

**Comment by dawhite** [comment]
IDL, especially the more traditional form of it, is quite different from C# and Java.  Attached to this response is a BETA version of what I have come up with.  I tested it with a large number of MOD11A2 tiles and it worked as expected.  I will not be able to post an official release for at least a few more days.  The following example does not mirror everything you're trying to do, but making changes will not be difficult.

```
pro batch_test_program
  compile_opt idl2
 
  mod11a2_dir = 'C:\mrt_testing\'
  mod11a2_files = file_search(mod11a2_dir, 'MOD11A2*.hdf', /fold_case, count=file_count)
  if file_count eq 0 then return

  grid_name = 'MODIS_Grid_8Day_1km_LST'
  sd_names = ['LST_Day_1km']
 
  output_projection = envi_proj_create(/geographic)
  ;specifying output pixel size is now OPTIONAL, but ensures consistency across tiles
  output_pixel_size = [0.0083650927991d, 0.0083650927991d]
  background = 0.0d
  
  for i=0,file_count-1 do begin

    file_split = strsplit(file_basename(mod11a2_files[i]),'.',/extract)
    output_rootname = strjoin(file_split[0:n_elements(file_split)-2],'.') + '_LST_Day_1km'

    output_method = 1

    interpolation_method = 1

    convert_modis_data, in_file=mod11a2_files[i], $
      out_path=mod11a2_dir, out_root=output_rootname, $
      gd_name=grid_name, sd_names=sd_names, out_ps=output_pixel_size, $
      out_method=output_method, out_proj=output_projection, $
      interp_method=interpolation_method, background=background, $
      r_fid_array=r_fid_array, r_fname_array=r_fname_array, $
      msg=msg
   
    if msg ne '' then print, msg
  
  endfor
  
end
```  
[mctk.zip](https://github.com/dawhite/MCTK/files/94893/mctk.zip)

**Comment by am2222** [comment]
dear dawhite ,
Thank you so much for your help and the time..I am working on the method you have sent I'll say the result..IDL is working on files right now

**Comment by am2222** [comment]
dear dawhite ,
Thank you so much,The code you have provided works great,But After a while idl gives an error,I thing it is because of huge number of files(470 files)..I should stop processing and again start it again with reminding of files...


I have also another question,,I want to do the same with mod13a3 products..But I dont know where to find SD_Names of NDVI,I have set is to '1km monthly NDVI' but it seems it does nothing and msg is also empty...Could you please give me a hint where to find sd_names?

Thank you for your help and the time 
With kind regards,
Majid

**Comment by am2222** [comment]
I have tested this code with mod13a3 and I get again this code
WIDGET_BASE: Invalid widget identifier: 19.
read file            1 of          111


Is sth wrong with my code?Could you give me some hints?
Thank you again 


pro batch_mod13a
  compile_opt idl2

  mod13a3_dir = 'D:\hdf\'
  mod13a3_files = file_search(mod13a3_dir, 'MOD13A3*.hdf', /fold_case, count=file_count)
  if file_count eq 0 then return

  grid_name = 'MOD_Grid_monthly_1km_VI'
  sd_names = ['1km monthly NDVI' ]

  output_projection = envi_proj_create(/geographic)
  ;specifying output pixel size is now OPTIONAL, but ensures consistency across tiles
  output_pixel_size = [0.0083650927991d, 0.0083650927991d]
  background = 0.0d

  for i=0,file_count-1 do begin
    print,'read file '+ string(i) + ' of '+string(file_count-1)
    file_split = strsplit(file_basename(mod13a3_files[i]),'.',/extract)
    output_rootname = strjoin(file_split[0:n_elements(file_split)-2],'.') + '_ndvi_'

    output_method = 1

    interpolation_method = 1

    convert_modis_data, in_file=mod13a3_files[i], $
      out_path=mod13a3_dir, out_root=output_rootname, $
      gd_name=grid_name, sd_names=sd_names, out_ps=output_pixel_size, $
      out_method=output_method, out_proj=output_projection, $
      interp_method=interpolation_method, background=background, $
      r_fid_array=r_fid_array, r_fname_array=r_fname_array, $
      msg=msg

    if msg ne '' then print, msg

  endfor

end

**Comment by dawhite** [comment]
sd_names = ['1km monthly NDVI' ] should be sd_names = ['1 km monthly NDVI']

**Comment by dawhite** [comment]
And if you want to avoid getting that widget error when running ENVI in full batch mode, be sure to include /no_status_window when you call the envi_batch_init function.  If you ever process swath files in full batch mode, you should include the /no_msg keyword as well.  That way no progress windows of any kind will show up.

**Comment by am2222** [comment]
Dear dawhite,
Thank you for your helps...I have set sd_names = ['1 km monthly NDVI'] and code works fine..
Thank you very much
