### ISSUE TITLE
"convert_modis_data" not activated

### ISSUE THREAD

**Issue by zxy1219** [dawhite/MCTK#13]
Hi, I'm using the IDL + ENVI to process the MOD12A3 data. The MCTK GUI works very well, but the function "convert_modis_data" never become activated in IDL. I have the mctv.sav and modis_products.scsv in both save_add and extensions folders. It seems someone reported the similar problems online. But I haven't find out the solution.

Would you please provide a advise?

Thanks!

**Comment by dawhite** [comment]
If you can access the GUI version of MCTK in both ENVI and ENVI Classic, then the plugin is correctly installed.  The GUI calls that exact function behind the scenes when you process a file.  To use the function directly, ENVI has to be running within the IDL environment.  That requires you to type ENVI() or ENVI at the command line or include one of them at the start of a program.  The first one launches ENVI, the second ENVI Classic.  If you are using a program, you have to decide if you want to run ENVI in regular or batch mode while doing so.  The documentation for both versions of ENVI covers how to specify that.
