### ISSUE TITLE
MCTK 2.1.4 

### ISSUE THREAD

**Issue by shubek** [dawhite/MCTK#14]
Hi, I am trying to use MCTK (v 2.1.4) in ENVI 5.1 to georeference MODIS Level 2 swath snow product (MYD10_L2). However, I am getting an error 'Tag name BOWTIE is undefined for structure'. I was wondering why I am getting this error? I would greatly appreciate your advice. Thank you.

**Comment by dawhite** [comment]
I'm betting that you have an older version of MCTK installed somewhere.  I'd search for "modis_conversion_toolkit.sav" or other copies of "mctk.sav" in the Exelis/Harris folder, as well as your save_add and extensions folders if they are in different locations.  If you find any, delete them and all associated support files, then restart ENVI.

**Comment by shubek** [comment]
You are right. Thank you so much!
