### ISSUE TITLE
Question_MSTK

### ISSUE THREAD

**Issue by Morteza1395** [dawhite/MCTK#15]
Hi Dear all
 I'm going to georeference several MODIS image(300) and product(300).I can not find some function in MCTK such as "convert_modis_data","mctk_create_bridges" and ' mctk_destroy_bridges''and etc. Where can I download this file?

**Comment by dawhite** [comment]
Those functions are contained with the mctk.sav file. If you follow the installation instructions provided in the user guide, the functions will be available the next time you start ENVI (you should see "% Restored file: MCTK." in the IDL console).  It's a lot like installing an R or Python package.  To test function presence, type this at the command line: help, names='convert_modis_data', /routines, /full. You still need to construct a program that will loop through your files and process them. MCTK does not provide that functionality on its own.

**Comment by Morteza1395** [comment]
Thank you your your reply and great guide. I did do the above-mentioned tasks and saw "% Restored file: MCTK." in the IDL console but  do not active those functions such as "convert_modis_data".

**Comment by Morteza1395** [comment]
please find attach.
http://s8.picofile.com/file/8286240318/Screenshot_2017_02_13_17_00_28.png

**Comment by dawhite** [comment]
They show up the same way for me, too, but they are there and they do work.  They used to appear as highlighted routines, but not any more and I have no control over that.  That is why I recommended you type this at the command line and hit enter to demonstrate that the routines are available: 

help, names='convert_modis_data', /routines, /full

If you are looking for a description of the convert_modis_data routine and its keywords, the user guide has that, starting on page 13.  Relying on hover help is not recommended.

**Comment by Morteza1395** [comment]
yes, they are there but they don't work. I type "help, names='convert_modis_data', /routines, /full" at the command line and I saw this 'CONVERT_MODIS_DATA   BACKGROUND BRIDGES CALIB_METHOD DEFAULT_UTM FILL_REPLACE_VALUE GD_NAME GEOLOC_FILE INTERP_METHOD IN_FILE MSG NO_MSG OUT_METHOD OUT_PATH OUT_PROJ OUT_PS OUT_ROOT PROGRESS R_FID_ARRAY R_FNAME_ARRAY SD_NAMES SD_POS SWT_NAME USE_DOUBLE '
 but this function distinctive in multiple document panel. so, where is problem? What is your guess?

**Comment by Morteza1395** [comment]
Front  'Compiled Functions:' is empty in command line, and 'convert_modis_data' function is black in multiple document panel.

**Comment by dawhite** [comment]
'Compiled Functions' is blank because the routine is a procedure, not a function. You'll see "Compiled Procedures' in the IDL Console right above what you pasted: 'CONVERT_MODIS_DATA BACKGROUND BRIDGES CALIB_METHOD...'  If a routine is accessible at the command line, it is available to programs you write in the editor once they are compiled and executed. The examples I provide with the plugin are just that: examples. You will have to modify the one that is most appropriate for the data you are trying to process. I'm getting the impression that you are very new to IDL. I recommend consulting tutorials available online and, if needed, contacting Harris technical support. They can point you to additional programming resources.

**Comment by Morteza1395** [comment]
pro MODorMYD
  compile_opt idl2
 
 Open=envi_pickfile(title='Open first Image File (KM_MOYD02)',default=MODorMYD_dir, filter='*.hdf')
  if (Open eq '') then return
  MODorMYD_dir=strmid(Open,0,strpos(Open,'\', /REVERSE_SEARCH))
  MODorMYD_files = file_search(MODorMYD_dir, '*.hdf', /fold_case, count=file_count)

  if file_count eq 0 then return
  background = 0.00
  sd_pos=[0,2,3]
  
;do not put the bridge creation/destruction code inside a loop
bridges = mctk_create_bridges()

  for i=0,file_count-1 do begin
    print,'read file '+ string(i) + ' of '+string(file_count-1)
    file_split = strsplit(file_basename(MODorMYD_files[i]),'.',/extract)
    output_rootname ='/'+ strjoin(file_split[0:n_elements(file_split)-2],'.') 

    ;Output method schema is:
    ;0 = Standard, 1 = Projected, 2 = Standard and Projected
     output_method = 1
     output_projection = envi_proj_create(/geographic)
     
    ;Calibration method schema is:
    ;0 = Radiance / Emissivity, 1 = Reflectance / Emissivity, 2 = Radiance / Brightness Temp
    calib_method = 0
    
    ;Choosing linear interpolation
    interpolation_method = 1
      
    convert_modis_data, in_file=MODorMYD_files[i], out_path=MODorMYD_dir, $
      out_root=output_rootname, out_method=output_method, $
      interp_method=interpolation_method, $
      out_proj=output_projection, calib_method=calib_method, $
      sd_pos=sd_pos, /no_msg, background=background, r_fid_array=r_fid_array, $
      r_fname_array=r_fname_array, bridges=bridges, msg=msg
    mctk_destroy_bridges, bridges

SAVE, FILENAME='MODorMYD.sav'  
endfor
end
------------------------------------------------------------------------------------
thank you very much this program is run but I have two question follow as:
1- how to select several band from MODIS image? for example I need just  31 and 32 bands from KM MODIS image.

2- I want them not to be modified by others, I create .sav file and restored but I cannot run this file. What is problem solving?
