### ISSUE TITLE
Protect Source Code

### ISSUE THREAD

**Issue by Morteza1395** [dawhite/MCTK#16]
I have .pro cod  which I want them not to be modified by others. how could i convert .sav into read only files?

I do the Steps include follow as:
1. Reset your session 
IDL>.FULL_RESET_SESSION or
IDL>.F
2. Open the ENVI procedure (*.pro)
IDL> .COMPILE my_envi_function.pro
3. Call RESOLVE_ALL 
IDL> Resolve_All, /continue_on_error, skip_routines='envi'
4. Create the ENVI save file (*.sav) 
IDL> SAVE, file='my_envi_function.sav', /routines

but when deleted .pro file then, .sav file is deactivate!!!!??

**Comment by dawhite** [comment]
That is a basic ENVI+IDL programming question. This is not the place to ask it. To learn more about creating distributable applications, go here: https://www.harrisgeospatial.com/docs/ToolboxExtensions.html. If you need help with this process, I recommend you contact Harris technical support.
