### ISSUE TITLE
Too much fill value in MOD04_L2 or MOD04_3K

### ISSUE THREAD

**Issue by Boorn123** [dawhite/MCTK#18]
Hello Devin,
Thank you for your excellent toolkit. I extracted and reprojected AOD images from the MOD04_3K dataset using the MCTK 2.17. To my knowledge, the valid values of AOD are usually  spatially continuous, so are the bad or fill value. But I found that many fill values appear within the good part of my resulting AOD images, so as to form a fishnet.  This is not good for my study. And this does not occur in previous versions, but MOD04_3K is not applicable. 
As a newcomer of programming, could you please tell me the reasons or give me any suggestions?
 I really appreciate your help.

Boorn

**Comment by dawhite** [comment]
Please provide an image (screenshot) that demonstrates this issue, along with the filename of the granule used to produce the image. What output pixel size are you specifying?

**Comment by Boorn123** [comment]
These two images are obtained from the same dataset MOD04_L2.A2014187.0330.006.2015075205649.hdf using MCTK 2.1.7 and 1.x, respectively. I do not know the exact version of 1.x, but I know the Users_Guide.pdf is revised in 07/22/12. Everything but the MCTK version is the same. Why does the first image have so  many fill values that do not appear in the second image? 
![_10km_217](https://user-images.githubusercontent.com/20023160/34088293-660d4988-e3e3-11e7-99af-6b065ff5ff94.png)
![_10km_old](https://user-images.githubusercontent.com/20023160/34088294-66e2e4d0-e3e3-11e7-8a2f-ca24ac240c9c.png)
I am not quite sure about the output pixel size, and my IDL codes are as follows:
The first IDL code (2.1.7):
    out_method = 1
    units = ENVI_TRANSLATE_PROJECTION_UNITS('Meters')
    datum = 'WGS-84'
    interpolation_method = 6
    swath_name = 'mod04'
    sd_names = ['Image_Optical_Depth_Land_And_Ocean']
    filecount = SIZE(input_filenames, /DIMENSIONS)
    bridges = mctk_create_bridges()
    out_projection = ENVI_PROJ_CREATE(/utm, zone=50, datum=datum, units=units)
    filename = 'MOD04_L2.A2014187.0330.006.2015075205649.hdf'
    convert_modis_data, IN_FILE = filename, OUT_PATH = output_directory, $
        OUT_ROOT = out_rootname, SWT_NAME = swath_name, OUT_METHOD = out_method, $
        INTERP_METHOD = interpolation_method, SD_NAMES = sd_names, $
        /NO_MSG, OUT_PROJ = out_projection, bridges=bridges, msg=msg,$
        BACKGROUND = -99, FILL_REPLACE_VALUE = -99,r_fid_array=r_fid_array, r_fname_array = 
        r_fname_array
    mctk_destroy_bridges, bridges

The second IDL code (1.x):
    out_method = 1
    units = ENVI_TRANSLATE_PROJECTION_UNITS('Meters')
    datum = 'WGS-84'
    interpolation_method = 6
    swath_name = 'mod04'
    sd_names = ['Image_Optical_Depth_Land_And_Ocean']
    out_projection = ENVI_PROJ_CREATE(/utm, zone=50, datum=datum, units=units)
    filename = 'MOD04_L2.A2014187.0330.006.2015075205649.hdf'
    convert_modis_data, IN_FILE = filename, OUT_PATH = output_directory, $
        /higher_product,/swath, OUT_ROOT = out_rootname, $
        SWT_NAME = swath_name, OUT_METHOD = out_method, $
        INTERP_METHOD = interpolation_method, SD_NAMES = sd_names, $
        /NO_MSG, OUT_PROJ = out_projection, NUM_X_PTS = 50,NUM_Y_PTS = 50, $
        BACKGROUND = -99, FILL_REPLACE_VALUE = -99,r_fid_array=r_fid_array, r_fname_array = 
        r_fname_array

**Comment by Boorn123** [comment]
Thank you so much, @dawhite . The result is good as you said.
