### ISSUE TITLE
NaN problem

### ISSUE THREAD

**Issue by BarryBA** [dawhite/MCTK#20]
Thank you for your plugin to process MODIS data. However, after my processing of MODIS L1B data by MCTK, I found the value of some pixels are NaN, I wonder to konw the reasons. thank you!

**Comment by dawhite** [comment]
NaN is the default value used for fill (bad pixels identified by the data provider) and for background (areas in projected/reprojected output that contain no valid data. You'll see fields for "Fill" and "Background" in the MCTK interface. If you would like to use a different value, like -999, simply enter it in those fields before processing your data.

**Comment by BarryBA** [comment]
Thanks for your reply. So, it's the problem of origin data which have some bad pixels or no valid data, thank you very much!

**Comment by dawhite** [comment]
Yes, but the actual fill value used by the data provider (e.g., NASA) for bad pixels could be something like 32767, for example. MCTK detects that value and allows you to substitute a different value that might be more useful for you. When you project data, you are putting it into a new coordinate space and there will be regions that contain no valid data (background). It is up to you to decide what value you want to use for those areas. Some people use one value for bad pixels and another for background so they can track them separately.
