### ISSUE TITLE
Hello,Can cmtk batch read and bulk process hdf?

### ISSUE THREAD

**Issue by max19951001** [dawhite/MCTK#21]
Can cmtk batch read and bulk process hdf?

**Comment by dawhite** [comment]
Yes. That is covered in the user guide. You will have to write a program in IDL to do it. The programming interface is described at the back of the user guide and sample programs are provided for *single* file processing. You will have to extend the one you want to handle multiple files.

**Comment by dawhite** [comment]
Yes, and that's why there is an API, which enables batch operations. If you're that opposed to IDL, MRT and MRTSwath are alternatives, but their batch processing requires using the command line. The GDAL-based options out there (e.g., GRASS and QGIS) use Python interfaces. You're going to have to do at least some basic scripting no matter which one you choose. It sounds like what you really want is interactive batch processing, i.e., point-and-click.

**Comment by max19951001** [comment]
Yes,i hope there have a GUI for mctk,including batch processing. Because it is very convenient for people who have no programming basis.If no have GUI,i will have to learn IDL.

**Comment by dawhite** [comment]
Okay, I'll add that request to the feature backlog

**Comment by max19951001** [comment]
Hello dawhite,can mctk  resize the  data ？i have not see  it 。

**Comment by dawhite** [comment]
For grid data, you can input the desired spatial resolution. For swath data, you need to let it generate output at native spatial resolution, which is computed internally. This is due to how the data are collected and processed before being distributed. If you want to resize MCTK's output, ENVI and many other applications have ways to easily do that.

**Comment by max19951001** [comment]
Hello dawhite,there have some problems about batch processing mod 04 ？
pro modis_mctk
  compile_opt idl2
  e=envi(/headless)
  modis_swath_file = 'D:\MYD04\MYD04_L2.A2005100.0505.061.2018023034118.pscs_000501310666.hdf'
  output_location = 'D:\mod\'
  output_rootname = 'max'
  swath_name = 'MYD04'
  sd_names = ['AOD_550_Dark_Target_Deep_Blue_Combined']

  ;Output method schema is:
  ;0 = Standard, 1 = Projected, 2 = Standard and Projected
  out_method = 1
  output_projection = envi_proj_create(/geographic)
  ;Choosing nearest neighbor interpolation
  interpolation_method = 0
  ;do not put the bridge creation/destruction code inside a loop
  bridges = mctk_create_bridges()

  convert_modis_data, in_file=modis_swath_file, $
    out_path=output_location, out_root=output_rootname, $
    swt_name=swath_name, sd_names=sd_names, $
    out_method=out_method, out_proj=output_projection, $
    interp_method=interpolation_method, /no_msg, $
    r_fid_array=r_fid_array, r_fname_array=r_fname_array, $
    bridges=bridges, msg=msg,/progress

  mctk_destroy_bridges, bridges


end

No results after running the program

**Comment by max19951001** [comment]
when i change the value "swath_name="MYD04" to "swath_name="mod04",idl control print "HDF_SD_ATTRFIND: Unable to find the HDF-SD attribute named _Scale.
% HDF_SD_ATTRFIND: Unable to find the HDF-SD attribute named _Offset"

and i want to known hou to get "swath_name"

**Comment by max19951001** [comment]
when i change the value "swath_name="MOD04",the result is coming out

**Comment by max19951001** [comment]
![image](https://user-images.githubusercontent.com/16135879/55694872-b70edc80-59e8-11e9-8d7c-ad7b9e7f27d5.png)

this is  the result that HDF view open mod 04 

![image](https://user-images.githubusercontent.com/16135879/55694916-f1787980-59e8-11e9-84ec-0f8277a89567.png)

**Comment by dawhite** [comment]
The HDF_SD_ATTRFIND messages about scale and offset are normal. Not every MODIS product has those attributes, but MCTK always looks for them, just to be safe. I was going to recommend that you use HDFView or the interactive version of MCTK to figure out what the swath name is. That value is set by the data producer and it is not always consistent with the collection platform (Terra vs. Aqua).

**Comment by max19951001** [comment]
@dawhite  thanks,The HDF_SD_ATTRFIND messages will not affect the final result.
