### ISSUE TITLE
Question about the data value.

### ISSUE THREAD

**Issue by BarryBA** [dawhite/MCTK#22]
Hi, I have processed the MODIS L1B data via the MCTK toolkit. The original data has been processed into the Reflectance and Emissive data.
But I found the maxmium value of some spectral bands is higher than 1.0. 
Why is it happen? Shouldn't the data is in the range of 0 to 1.0?

**Comment by BarryBA** [comment]
![image](https://user-images.githubusercontent.com/35425412/53959438-9b30c600-411e-11e9-91da-a96e46b07715.png)
This is how I used the toolkit to process MODIS L1B data.

**Comment by dawhite** [comment]
Yes, reflectance values should stay within the range of 0.0 to 1.0. MCTK uses the scale factor supplied by NASA with each HDF file to convert raw digital numbers to reflectance, so the issue is not with MCTK. What you're seeing is not uncommon, though. Many reflectance conversion algorithms overestimate or underestimate reflectance, so you will find values that fall below 0.0 or above 1.0 because they are using relatively simple approaches to solve a complex problem. Especially for Top of Atmosphere (TOA) reflectance, which is what NASA provides in Level 1B products.

**Comment by BarryBA** [comment]
> Yes, reflectance values should stay within the range of 0.0 to 1.0. MCTK uses the scale factor supplied by NASA with each HDF file to convert raw digital numbers to reflectance, so the issue is not with MCTK. What you're seeing is not uncommon, though. Many reflectance conversion algorithms overestimate or underestimate reflectance, so you will find values that fall below 0.0 or above 1.0 because they are using relatively simple approaches to solve a complex problem. Especially for Top of Atmosphere (TOA) reflectance, which is what NASA provides in Level 1B products.

Ok, thanks for your reply.
What about the emissivity? what should the range of the emissivity be?
In my data, the emissivity of some bands is between 0~16.0.  Is it common?

**Comment by dawhite** [comment]
What you actually receive for the emissive bands is radiance data in Watts per square meter per micrometer per steradian (W/m2/um/sr), not emissivity, so values on the order of 16 is normal. Here are links to the MODIS L1B User's Guide and Algorithm Theoretical Basis Document where you can learn more about the emissive bands:

https://mcst.gsfc.nasa.gov/sites/default/files/file_attachments/M1054.pdf
https://mcst.gsfc.nasa.gov/sites/default/files/file_attachments/MODIS_L1B_ATBD_ver4.pdf

The use of "emissivity" in MCTK is a holdover from the early days of plugin development when I was debating how to label the conversion options and distinguish between the reflective and emissive bands. I should clarify that to avoid confusion over what MCTK actually outputs.

**Comment by BarryBA** [comment]
> What you actually receive for the emissive bands is radiance data in Watts per square meter per micrometer per steradian (W/m2/um/sr), not emissivity, so values on the order of 16 is normal. Here are links to the MODIS L1B User's Guide and Algorithm Theoretical Basis Document where you can learn more about the emissive bands:
> 
> https://mcst.gsfc.nasa.gov/sites/default/files/file_attachments/M1054.pdf
> https://mcst.gsfc.nasa.gov/sites/default/files/file_attachments/MODIS_L1B_ATBD_ver4.pdf
> 
> The use of "emissivity" in MCTK is a holdover from the early days of plugin development when I was debating how to label the conversion options and distinguish between the reflective and emissive bands. I should clarify that to avoid confusion over what MCTK actually outputs.

Ok, now I understand.
Based on the option seletion in the above screenshot, the reflective solar bands (RSB) will generate the top of the atmosphere (TOA) reflectance factors, while the thermal emissive bands (ESB) will generate the TOA radiances.
Thank you very much. A great help to me.

**Comment by dawhite** [comment]
Yes. And I just noticed that you're apparently using a very old version of MCTK. It looks to be from 2008, which makes it more than ten years old. Please download and install the latest version from the Releases section. I've fixed a lot of bugs and performance issues over the years. https://github.com/dawhite/MCTK/releases

**Comment by BarryBA** [comment]
> Yes. And I just noticed that you're apparently using a very old version of MCTK. It looks to be from 2008, which makes it more than ten years old. Please download and install the latest version from the Releases section. I've fixed a lot of bugs and performance issues over the years. https://github.com/dawhite/MCTK/releases

I used the new version of MCTK in ENVI software. But when I input the data, it prompt the error:
![image](https://user-images.githubusercontent.com/35425412/54095449-5b016a00-43e2-11e9-8b87-6390e1967fda.png)
what's the problem?

**Comment by dawhite** [comment]
Remove your old version, restart ENVI, and the error message should go away

**Comment by BarryBA** [comment]
> Remove your old version, restart ENVI, and the error message should go away

Wow. Thanks a lot. It works now.
By the way, if we want to cite the toolkit MCTK in research papers, how to write?

**Comment by dawhite** [comment]
There is no one set way to do it, since it depends on the publication style you're required to use, but in general you can use something this:

White, D. A. (2018). MODIS Conversion Toolkit Version 2.1.9. Retrieved from https://github.com/dawhite/MCTK.
