### ISSUE TITLE
IDL8.5, MCTK-2.1.11, "keyword GRID not allowed in call to: CONVERT_MODIS_DATA"

### ISSUE THREAD

**Issue by BennyZ-7** [dawhite/MCTK#25]
Dear Dawhite：
When I use the MCTK-2.1.11, the error is about "**keyword GRID not allowed in call to: CONVERT_MODIS_DATA**". I read your comments about “Jennyzht” on 16 Dec 2017(“https://github.com/dawhite/MCTK/issues/7”). And I delete older version of the MCTK, But the error still exists. Besides. I read some answers, which about path conflict and path priority. Whereas, I didn’t do it. Can you help me, and give me some advice?
Cheers,
ZB
[code.docx](https://github.com/dawhite/MCTK/files/5438429/code.docx)
![code](https://user-images.githubusercontent.com/73472624/97166052-93c0a380-17bf-11eb-8f37-50d47c9b4bab.png)

**Comment by dawhite** [comment]
It looks like you tried to repurpose code that uses the old version of the MCTK programming interface. The error message seems to be tied to your use of the /grid keyword, which you are including in your call to convert_modis_data. The keyword is no longer part of the interface. Please consult the user guide that comes with the latest version. There are example programs in the back, along with a full description of the interface, that should help you.

**Comment by BennyZ-7** [comment]
Thank you very much! I made a ridiculous mistake. Thank you again! You really helped me! Well, whether only MRT can process batch mosaicking?

**Comment by dawhite** [comment]
ENVI has a built-in mosaicking function that can be called programmatically. It's called MOSAIC_DOIT in ENVI Classic and MosaicRaster in the new version. It didn't make sense to recreate that for MCTK. Once you have all of your desired output, you can use that function to create a single large product.

**Comment by BennyZ-7** [comment]
Thanks for your quick respond of my questions and further guiding！ I really appreciate that.
