### ISSUE TITLE
IDL8.5, MCTK-2.1.11，reprojection'h27v05' 'h28v05' 'h28v06' 'h29v06'

### ISSUE THREAD

**Issue by BennyZ-7** [dawhite/MCTK#26]
Dear dawhite:
I'm sorry to bother you again. I have a new problem when I try to **batch re-project  mosaiced HDF data**. **The mosaiced HDF data including 'h27v05' 'h28v05' 'h28v06' 'h29v06'**. And I can't running successfully. The IDL and ENVI just **unreacted**. Consequently, could you tell me what to do?  There are my codes , mosaiced HDF data's map info (which is mosaiced MOD11A2_2000065.HDF) and unreacted information.  Thanks!
Cheers,
ZB
![image](https://user-images.githubusercontent.com/73472624/98089769-2fd46400-1ebe-11eb-8b5a-9b3512650656.png)
![image](https://user-images.githubusercontent.com/73472624/98089518-cb190980-1ebd-11eb-900e-8895af15be0e.png)
![image](https://user-images.githubusercontent.com/73472624/98089732-22b77500-1ebe-11eb-8db2-958e7778c095.png)

**Comment by dawhite** [comment]
What will help you to troubleshoot your program is to add the msg keyword to your call to convert_modis_data. That will contain error messages encountered by MCTK during processing. Put the keyword at the end of your call, then on the next line, check to see if it has any content. If so, print it out.

convert_modis_data, ... , msg=msg
if msg ne '' then print, msg

**Comment by BennyZ-7** [comment]
The content is "**Selected file does not appear to be a valid MODIS dataset**". So, If I just mosaic ('h27v05' 'h28v05' 'h28v06' 'h29v06') four zones data  to a new integrated data, MCTK can't identify the new data?  Or did I rename the mosaiced data?

**Comment by dawhite** [comment]
If I'm understanding you correctly, you took four MODIS product files and mosaicked them together to create one new file, then tried to process that file with MCTK. Unless your mosaicking process creates a properly-formatted MODIS product file, MCTK will not accept it. Filename is part of it, but so is file format, internal file structure, and internal file metadata. Before writing a program to batch process a large number of files with MCTK, it is a good idea to take one of the files and process it manually using the GUI to see if it can be done. The user interface will report the same errors as the programming interface.

**Comment by BennyZ-7** [comment]
Dr.dawhite:
I'm sorry to reply you so late. Through this period of effort, I changed the MRT mosaicking code so that MCTK can recognize the new data. Thank you for your continued clarification ,although my poor English.
Best wishes for you!
ZB
