### ISSUE TITLE
MCTK: Unable to locate the specified swath. Check name against HDF file contents.

### ISSUE THREAD

**Issue by itnewstarfx** [dawhite/MCTK#27]
Dear dawhite,
When I run the example code from mctk user guide, I found that it's not success. The msg showed that Unable to locate the specified swath. Check name against HDF file contents. I want to know how to solve this problem. Thanks!

;Level 2 swath example
pro test_batch_modis_conversion_l2_swath
  compile_opt idl2

  ;modis_swath_file = 'C:\MCTK_Input\MOD07_L2.A2013173.0710.006.2013173195131.hdf'
  
  modis_swath_file = 'D:\TestData\MYD04\MYD04_L2.A2019001.0250.061.2019001165255.hdf'
  ;The specified output location MUST end in the appropriate path
  ;separator for your OS
  output_location = 'D:\Data\AOD\MODIS_10KM\TestResult\'

  output_rootname = 'MYD04_A2019001'

  swath_name = 'MYD04'

  sd_names = ['Optical_Depth_Land_And_Ocean']

  ;Output method schema is:
  ;0 = Standard, 1 = Projected, 2 = Standard and Projected
  out_method = 1

  output_projection = envi_proj_create(/geographic)

  ;Choosing nearest neighbor interpolation
  interpolation_method = 0

  ;do not put the bridge creation/destruction code inside a loop
  bridges = mctk_create_bridges()

  convert_modis_data, in_file=modis_swath_file, $
    out_path=output_location, out_root=output_rootname, $
    swt_name=swath_name, sd_names=sd_names, $
    out_method=out_method, out_proj=output_projection, $
    interp_method=interpolation_method, /no_msg, $
    r_fid_array=r_fid_array, r_fname_array=r_fname_array, $
    bridges=bridges, msg=msg
  print, msg
  mctk_destroy_bridges, bridges

end

**Comment by itnewstarfx** [comment]
![image](https://user-images.githubusercontent.com/82810718/115224330-5110d000-a13f-11eb-9ad4-5a070e90bcaf.png)

**Comment by dawhite** [comment]
I downloaded the file you're working with from this location:

https://ladsweb.modaps.eosdis.nasa.gov/archive/allData/61/MYD04_L2/2019/001/MYD04_L2.A2019001.0250.061.2019001165255.hdf

Looking at its contents in HDFView, your swath name is incorrect. It should be 'mod04'.

![image](https://user-images.githubusercontent.com/5896500/115230880-276d8f80-a0d2-11eb-81aa-11fa37265569.png)

**Comment by itnewstarfx** [comment]
Thank you for your answer. I have successfully resolve this problem. But, I meet a new problem.
When I use the code to process single hdf, it can get correct result. However, when I use a for loop to process multi hdfs, the program can not be success. The msg is 'OPENW: Error opening file. Unit: 100, File: ‪D:\Data\AOD\MODIS_10KM\TestResult\MYD04_L2_A2019001_0250_Swath_2D_1.dat'. How can I solve this problem? Thanks very much.
![image](https://user-images.githubusercontent.com/82810718/115232545-6854bb00-a149-11eb-8fd3-46279be1243c.png)

**Comment by dawhite** [comment]
That is a more general IDL programming question focused on batch processing. There are several resources available, including online tutorials, forums like the idl-pvwave group, and books. You can also contact L3Harris Geospatial technical support and request assistance with learning how to do batch programming: https://www.l3harrisgeospatial.com/Support/Technical-Support.

**Comment by itnewstarfx** [comment]
Dear dawhite,
Thank you for your answer. When I program with IDL using the function of openraster(), the problem 'Object reference type required in this context: E' appear. Could you give me a solution for this problem? Thank you very much.

**Comment by dawhite** [comment]
Again, that is a more general ENVI programming question. Please see my previous response regarding resources available online.
