### ISSUE TITLE
Modis_Products.scsv could not be found

### ISSUE THREAD

**Issue by RichMawdsley** [dawhite/MCTK#6]
Hi dawhite,

I'm currently trying to install the MCTK plugin into ENVI but have hit a strange wall.

I'm placing the two files (mctk.sav & modis_products.scsv) into the directories advised in the user guide..  When I open ENVI Classic, I can go into File>OpenExternalFile>EOS>MODIS Conversion Toolkit and it all opens as expected.

However when I open the normal ENVI, I can see MCTK in the extensions on the right hand side, but when I double click it, i get the error "Modis_Products.scsv could not be found".

The files are all in the same places i.e \extensions and \save_add and i've ensured security rights to the files are ok, so I'm abit stumped and hoping you can help.

Thanks,

Rich

**Comment by RichMawdsley** [comment]
Hi There,

Firstly, apologies for never replying to the below.. a mix of high workload, time off and all the usual bits all got in the way!

I thought I’d give you an update on this tho.  I have now since got it working in AppV! – Although I’m not sure it was to blame.

Using Process Monitor whilst calling the extension showed me the directory it was looking in for the files.

Location being in the Envi directory \IDL83\Products\Envi48.

This location didn't even exist in my installation, but manually creating the folders and then putting the files in there, it worked straight away!

So who know what was going on! But it’s all working now!

Thanks very much for your help.

Rich

**Comment by dawhite** [comment]
I'm relying on information provided by ENVI itself to get the search paths, so it's odd that the application is pointing to a location that doesn't exist on your system.  Glad to hear you got it working, though.
