### ISSUE TITLE
MCTK under IDL 8.5

### ISSUE THREAD

**Issue by jiaozhh** [dawhite/MCTK#7]
Hi dawhite,
When I used MCTK under IDL 8.5 to geolocate MOD09 files, at the step "Performing final grid operation" , MCTK was stuck and had no response. The timeout of thread of PC was also happened. I think the compatibility of MCTK may be the reason. Would you please check this?
Cheers, 
JZH

**Comment by dawhite** [comment]
If it's timing out at that stage, it likely has something to do with the IDL-IDL Bridge.  I haven't built or tested MCTK against ENVI 5.3/IDL 8.5 yet.  That will take some time.  For now, I recommend reinstalling the last version of ENVI (5.2) and running MCTK in that.

**Comment by jiaozhh** [comment]
OK, thanks!
Look forward to the release of new MCTK.

**Comment by Lamchin** [comment]
Dear Dawhite, I would like do georeference at the MCD43B2 and MCD43B4 of MODIS product but I couldn't how I do that? can you help me? Actually, I did the following the process (To install MCTK, place the “mctk.sav” and “modis_products.scsv” files in your ENVI save_add and/or extensions folder. The location of this folder will vary by operating system and ENVI version.
ENVI 4.4-4.8: Windows: c:\program files\itt\idlXX\products\enviXX\save_add
UNIX\Linux: /usr/local/itt/idl_X.X/products/envi_X.X/save_add
Mac: /applications/itt/idl_X.X/products/envi_X.X/save_add) but did not include MODIS conversion toolkit.

**Comment by dawhite** [comment]
First, it looks like you are trying to use an older version of MCTK.  Please download the latest one from the Releases page and follow the installation instructions in the user guide carefully.  Second, you didn't specify which operating system you are using or your version of ENVI. Note that only ENVI 5.0 and higher is supported right now.  Once installed, there are clear instructions in the user guide for how to process grid datasets like the ones you mentioned.

**Comment by Jennyzht** [comment]
when i use the MCTK, the error is about “Keyword parameters not allowed in call.”for the "convert_modis_data"line, can you help me, and tell me some advice

**Comment by dawhite** [comment]
It sounds like you have an older version of the plugin installed somewhere and it might be conflicting with the new one. The parameters have changed over time. Also be sure to consult the User Guide with the API at the back, which includes multiple example programs.
