### ISSUE TITLE
Error when geolocate MOD03 data

### ISSUE THREAD

**Issue by jiaozhh** [dawhite/MCTK#9]
The georeferenced Height data in MOD03 show wrong result as an attached figure.
![error](https://cloud.githubusercontent.com/assets/6754276/11432921/e8e15edc-94f1-11e5-9b87-590ac782cc4a.jpg)

This following is the used code:
PRO geolocate_MOD03
  COMPILE_OPT idl2
  
  FILE='E:\tmp\MOD03.A2008124.0415.006.2012243171834.hdf'
  output_location='E:\'
  rootname = 'M03'
  swath_name='MODIS_Swath_Type_GEO'
  sd_names='Height'
  
  ;Output method schema is:
  ;0 = Standard, 1 = Projected, 2 = Standard and Projected
  out_method = 1

  output_proj = ENVI_PROJ_CREATE(/geographic)
  
  ;the resampling method
  ;0 — Nearest neighbor
  ;1 — Linear
  ;2 — Cubic convolution
  interp_method = 0
  
  backvalue=0.0
  
  convert_modis_data, in_file=file, $
    out_path=output_location,out_root=rootname,$
    out_method=out_method,interp_method=interp_method,$
    out_proj=output_proj,background=backvalue,$
    swt_name=swath_name, sd_names=sd_names, $ 
    r_fname_array=r_fnames,msg=msg
END

**Comment by dawhite** [comment]
That is very strange. Attached is what comes out when I run MCTK on my end. It could be that you need to change the Image Tile Size in the ENVI Classic preferences to a larger value (at least 10MB), but the better solution would be to use the new version of MCTK with the upgraded projection engine.  I hope to release that in a few days.
![height_georef](https://cloud.githubusercontent.com/assets/5896500/11456999/79aa12c8-966a-11e5-800e-b0e772cdb2e0.jpg)

**Comment by jiaozhh** [comment]
OK. I wait for the new version. 
Cheers!

**Comment by dawhite** [comment]
The latest version (2.1.0) is now available on the releases page: https://github.com/dawhite/MCTK/releases

**Comment by jiaozhh** [comment]
Thank you very much. I have tested the new version, and the geolocated MOD03 band data are all right.
